# config/config.yml
development:
  perform_twitter: false
  perform_facebook: false

test:
  perform_twitter: false
  perform_facebook: false

production:
  perform_twitter: true
  perform_facebook: true
  fb_username:
  fb_password:
  twitter_username:
  twitter_password: