# config/config.yml
development:
  perform_twitter: false
  perform_facebook: false

test:
  perform_twitter: false
  perform_facebook: false

production:
  perform_twitter: true
  perform_facebook: true
  fb_username: none
  fb_password: none
  twitter_username: none
  twitter_password: none